const CART_ADD_ITEM = "CART_ADD_ITEM";
const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
const USER_SIGNUP_START = "USER_LOGIN_START";
const USER_SIGNUP_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_SIGNUP_ERROR = "USER_LOGIN_ERROR";
const USER_LOGIN_START = "USER_LOGIN_START";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
const USER_LOGOUT = "USER_LOGOUT";
const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
const CART_CLEAR = "CART_CLEAR";
const UPDATE_USER = "UPDATE_USER";
const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export {
  CART_ADD_ITEM,
  FETCH_PRODUCTS_START,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,
  FETCH_PRODUCT_SUCCESS,
  CART_REMOVE_ITEM,
  USER_LOGIN_START,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_ERROR,
  USER_LOGOUT,
  SAVE_SHIPPING_ADDRESS,
  USER_SIGNUP_START,
  USER_SIGNUP_SUCCESS,
  USER_SIGNUP_ERROR,
  SAVE_PAYMENT_METHOD,
  CART_CLEAR,
  UPDATE_USER,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_START,
  UPDATE_PRODUCT_FAIL,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_START,
  DELETE_PRODUCT_FAIL,
};
